### ISSUE TITLE
Improve addon support

### ISSUE THREAD

**Issue by samselikoff** [embermap/ember-cli-tailwind#7]
@dfreeman I tried using our new code in ember-cli-addon-docs, but I believe some of the logic doesn't work.

Adding this addon to Addon Docs and stepping through the debuggger, I saw [this line](https://github.com/embermap/ember-cli-tailwind/blob/master/index.js#L18) was true (and `includer.treePaths` was undefined). So `index.js` thought Addon Docs was an app. (Of course, the dummy app _is_ an app, which might be where I'm getting confused...)

I should probably get my thoughts down here, just because a lot has been in my head thus far.

My goal is for e-cli-tailwind to be "the way" to get Tailwind into an Ember app or addon. A few use cases I have in mind:

1. **I want to use Tailwind to style my app.** Install e-cli-tailwind, get the modules in `app/styles/tailwind/*` and go to town.
2. **I want to use Tailwind to style my addon's dummy app.**
3. **I want to use Tailwind to style some components my addon is shipping to host apps.**

(3) is what I'm interested in doing in Addon Docs - I want to use Tailwind classes to style `<docs-viewer>`, for example. And ideally I'd like to prefix them, in case host apps would like to use their own customized Tailwind to style their dummy app. (And eventually use postcss to strip unused classes).

We don't have to tackle all of this now of course, I just wanted to put my thoughts down. Also, in the Addon Docs design work I'm doing, I just imported a static build of tailwind.css, so I'm not blocked. But it would be really cool if we could get e-cli-tailwind working for addons (so we could restrict colors, keep styles maintainable and so on).

**Comment by dfreeman** [comment]
You're right something's not working, but I think we're on the same page about how folks should be able to consume the addon. 

> I saw this line was true (and includer.treePaths was undefined). So index.js thought Addon Docs was an app. 

You should see `included` get invoked twice, once for the dummy app and once for addon-docs itself. Corresponding to that, `ember g ember-cli-tailwind` in an addon should populate modules in `addon/styles`, and `ember g --dummy ember-cli-tailwind` should populate them in `tests/dummy/app/styles`.

The dummy app's Tailwind config will get compiled into a `tailwind.css` file that it can import from its `app.css`. The JS modules will be available under `dummy/styles/...`. I don't think the generator can find the dummy's `app.css` to add the import automatically, but it should work if the author adds it by hand, and that shouldn't be too hard to fix in the generator. 

The addon's Tailwind config will get compiled into CSS and automatically added to `vendor.css` — we don't have an easy way to stop that from happening, because it's just what Ember CLI does for free-floating addon CSS, but that seems likely to be ok.

Up to this point, I think all of this fits with both the goals you've described and the way the actual implementation works.

The thing that's broken (and I'm really not sure how I missed this the first time around) is that the addon's config modules are getting built incorrectly. This looks like a bug in Ember CLI. If I put something like this in a fresh addon in `addon/styles/module.js`:

```js
export default 'hello world';
```

The result in `vendor.js` will, weirdly, show up twice: once raw, once transpiled.

```js
;export default 'hello world';

;define('tailwind-test/styles/module', ['exports'], function (exports) {
  'use strict';

  Object.defineProperty(exports, "__esModule", {
    value: true
  });
  exports.default = 'hello world';
});
```

Testing with a couple different CLI versions, it looks like this started happening in 2.13 (up to that point, it worked fine) and is still happening in 3.0. Chatting with @turbo87 in Slack, it doesn't sound like this is likely to change, and even if it were we'd need to come up with some workaround for that pretty wide window of CLI versions.

How would you feel about moving the tailwind config from `{app,addon}/styles/tailwind` to `{app,addon}/tailwind`? I know you're a fan of the mental model of them _as_ your styles, but just technically that seems like it's going to be painful.

**Comment by samselikoff** [comment]
Interesting - and thank you so (again) much for digging into this!

I could be convinced. Few things off the top of my mind:

- Are we being a good "citizen" by adding a new top-level `tailwind` folder? I did this with Mirage, I think it's okay (especially because Mirage is used both for app dev and testing), but it does feel like we already have a good place for styling-related stuff in `{app,addon}/styles`.
- Maybe we could try filtering the `tailwind/*` directory out of the tree completely? So, we'd just use it at build-time to generate `tailwind.css`, and filter those modules out from the client's jsTree. (I know I want them to be importable in client-side code, but maybe to get this to MVP-status we could target the three initial use cases first, and think through a good strategy later to get that working).
- What about using `.scss` files with Sass Maps for the config data? (Feels like ES6 mods still the way to go tho...)

**Comment by dfreeman** [comment]
> Are we being a good "citizen" by adding a new top-level tailwind folder? I did this with Mirage, I think it's okay (especially because Mirage is used both for app dev and testing), but it does feel like we already have a good place for styling-related stuff in {app,addon}/styles.

My take is that adding `app/tailwind` would actually be a lot simpler than what Mirage is doing, since we'd just rely on the normal build behavior in all environments. Devs have always been free to put whatever files/directories they want in `app`/`addon`, and even ember-data is technically just an addon that encourages you to add a bunch of new top-level directories.

The thing that makes `{app,addon}/styles` weird is that the build tooling sees it as a totally separate tree that just happens to live inside of another tree, rather than just a subdirectory of the `app` or `addon` tree. Because of that, the semantics for the content you put in there get kind of weird. And (as we've learned) the CLI doesn't even make guarantees that putting anything other than stylesheets will behave consistently from version to version.

> Maybe we could try filtering the tailwind/* directory out of the tree completely? So, we'd just use it at build-time to generate tailwind.css, and filter those modules out from the client's jsTree.

The problem is that we don't have an easy way to reach out and change the contents of our parent's tree. _Adding_ things is easy (which is why we don't have this problem with apps — ember-cli actually filters JS out of `app/styles` automatically), but changing them is difficult. We could try registering a preprocessor that would give us access to the `addon` and `styles` trees in-flight, but that's a really hairy path to go down. `ember-css-modules` is full of odd workarounds and semver conditionals to handle all the subtle ways that those things change from version to version of the CLI, and it's a nightmare to maintain.

> What about using .scss files with Sass Maps for the config data? (Feels like ES6 mods still the way to go tho...)

Agreed ES6 modules feel better, and I also think parsing the Sass and turning it into CJS for the tailwind processor could wind up being a little complicated (plus that rules out anyone using a preprocessor other than Sass from using Tailwind)

**Comment by dfreeman** [comment]
Ah, sorry—should've been clearer 🙂

I can open up a PR tonight or tomorrow with that change

**Comment by samselikoff** [comment]
@dfreeman trying out #8 locally in addon-docs, a few questions:

1. `_buildTailwind()` is getting called twice, and the second time `this.tailwindInputPath` is undefined, so [this line](https://github.com/embermap/ember-cli-tailwind/blob/master/index.js#L53) blows up. This is because when I installed, and only generated for my `/addon` folder, and not `/tests/dummy` (which I think is a valid use case, esp. for getting started).

    I can fix this - was just going to add an extra guard making sure `tailwindInputPath` is defined before attempting the build. Does that sound reasonable?

    Also, while I have you I want to make sure I understand what's going on. Does `index.js` basically get called twice, once for the addon and once for the addon's dummy app?

2. Once I made that fix, the app did build. But I noticed that with `/addon`'s Tailwind was automatically added to the dummy app's `vendor.css`. Which is cool! The only thing is, before I was doing `@import 'tailwind'` at the top of my `addon/styles/addon.scss` file, which let me do things like `@extend .ml-4`, a Tailwind class that was now available. But now, I think it's being included after, so these classes aren't available yet.

    Also, it would be cool to use JS to `import` the values from the Tailwind modules, but I'm using Sass. If I were using JS to generate these one-off styles that would work.

    Just thinking through some solutions here. Could we make the built `tailwind` available to `addon/styles` tree so it can `@import` it? Any other ideas?

**Comment by samselikoff** [comment]
Love it, think this solves all my problems
